n_data = 10
routine_name = "((head (dyn . 0)))"
generations_per_datum = 10
problem_dir = "./trs/e1_head1"
deterministic = true
max_sample_depth = 4
n_crosses = 5
p_add = 0.5
p_keep = 0.5
variable_weight = 0.5
constant_weight = 0.25
function_weight = 0.25
selection = "probabilistic"
population_size = 5
tournament_size = 5
mutation_prob = 0.95
n_delta = 10
p_partial = 0.2
p_observe = 0.0
max_steps = 50
max_size = 500
